import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import "@/public/css/bootstrap.min.css";
import "@/public/css/fonts-molla.min.css";
import "@/public/vendor/line-awesome/css/line-awesome.min.css";
import '@/public/scss/plugins/owl-carousel/owl.carousel.scss';

import "@/public/scss/style.scss";
import Layout from "@/components/custom-layout";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
        
        <Script src="/js/jquery.min.js" />
      </body>
    </html>
  );
}
